language: ruby

dist: trusty
sudo: required

cache: bundler

bundler_args: --without production development

rvm:
  - 2.5.3

addons:
  - postgresql: "9.5"
  - chrome: stable

services:
  - postgresql

env:
  - SECRET_KEY_BASE="c3922aff7d205a3d509d205e1173728dd341724630e16fd8410089d8d58503ac05aadbcabc45e5f67f9127e93d5e4447d1c8beb2f2548e91b8ba638e33532c36" MAILER_SENDER=foo@bar.com

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox
  - gem update --system
  - gem install bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rspec
