language: ruby

dist: trusty
sudo: required

cache: bundler

bundler_args: --without production development

rvm:
  - 2.4.1

addons:
  postgresql: "9.5"
  chrome: stable

services:
  - postgresql

env:
  - SECRET_KEY_BASE="c3922aff7d205a3d509d205e1173728dd341724630e16fd8410089d8d58503ac05aadbcabc45e5f67f9127e93d5e4447d1c8beb2f2548e91b8ba638e33532c36" MAILER_SENDER=foo@bar.com

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rspec
